adb shell pm uninstall -k --user 0 android.bips
adb shell pm uninstall -k --user 0 android.bookmarkprovider
adb shell pm uninstall -k --user 0 android.browser
adb shell pm uninstall -k --user 0 android.calendar
adb shell pm uninstall -k --user 0 android.cellbroadcastreceiver
adb shell pm uninstall -k --user 0 android.cellbroadcastreceiver.overlay.common
adb shell pm uninstall -k --user 0 android.chrome
adb shell pm uninstall -k --user 0 android.deskclock
adb shell pm uninstall -k --user 0 android.dreams.basic
adb shell pm uninstall -k --user 0 android.dreams.phototable
adb shell pm uninstall -k --user 0 android.egg
adb shell pm uninstall -k --user 0 android.emergency
adb shell pm uninstall -k --user 0 android.hotwordenrollment.okgoogle
adb shell pm uninstall -k --user 0 android.mms
adb shell pm uninstall -k --user 0 android.mms.service
adb shell pm uninstall -k --user 0 android.printspooler
adb shell pm uninstall -k --user 0 android.providers.downloads.ui
adb shell pm uninstall -k --user 0 android.providers.partnerbookmarks
adb shell pm uninstall -k --user 0 android.sharedstoragebackup
adb shell pm uninstall -k --user 0 android.statementservice
adb shell pm uninstall -k --user 0 android.stk
adb shell pm uninstall -k --user 0 android.wallpaper.livepicker
adb shell pm uninstall -k --user 0 android.wallpaperbackup
adb shell pm uninstall -k --user 0 android.wallpapercropper
adb shell pm uninstall -k --user 0 asurion.android.protech.att
adb shell pm uninstall -k --user 0 asurion.android.verizon.vms
adb shell pm uninstall -k --user 0 att.android.attsmartwifi
adb shell pm uninstall -k --user 0 att.dtv.shaderemote
adb shell pm uninstall -k --user 0 att.myWireless
adb shell pm uninstall -k --user 0 att.tv
adb shell pm uninstall -k --user 0 boxer.app
adb shell pm uninstall -k --user 0 cn.wps.moffice_eng
adb shell pm uninstall -k --user 0 cnn.mobile.android.phone.edgepanel
adb shell pm uninstall -k --user 0 com.afmobi.boomplayer
adb shell pm uninstall -k --user 0 com.android.apps.tag
adb shell pm uninstall -k --user 0 com.android.bookmarkprovider
adb shell pm uninstall -k --user 0 com.android.calendar
adb shell pm uninstall -k --user 0 com.android.chrome
adb shell pm uninstall -k --user 0 com.android.egg
adb shell pm uninstall -k --user 0 com.android.emergency
adb shell pm uninstall -k --user 0 com.android.gallery3d
adb shell pm uninstall -k --user 0 com.android.htmlviewer
adb shell pm uninstall -k --user 0 com.android.imedia.syncplay
adb shell pm uninstall -k --user 0 com.android.mbash
adb shell pm uninstall -k --user 0 com.android.mediacenter
adb shell pm uninstall -k --user 0 com.android.printspooler
adb shell pm uninstall -k --user 0 com.android.providers.calendar
adb shell pm uninstall -k --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall -k --user 0 com.android.stk
adb shell pm uninstall -k --user 0 com.android.stk2
adb shell pm uninstall -k --user 0 com.android.vending
adb shell pm uninstall -k --user 0 com.android.wallpaper.livepicker
adb shell pm uninstall -k --user 0 com.aura.oobe.samsung.gl
adb shell pm uninstall -k --user 0 com.booking
adb shell pm uninstall -k --user 0 com.example.android.notepad
adb shell pm uninstall -k --user 0 com.facebook.appmanager
adb shell pm uninstall -k --user 0 com.facebook.katana
adb shell pm uninstall -k --user 0 com.facebook.services
adb shell pm uninstall -k --user 0 com.facebook.system
adb shell pm uninstall -k --user 0 com.facemoji.lite.transsion
adb shell pm uninstall -k --user 0 com.funbase.xradio
adb shell pm uninstall -k --user 0 com.gallery20
adb shell pm uninstall -k --user 0 com.GMA.Ball.Sort.Puzzle
adb shell pm uninstall -k --user 0 com.gma.water.sort.puzzle
adb shell pm uninstall -k --user 0 com.google.android.apps.docs
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.docs
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.sheets
adb shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.slides
adb shell pm uninstall -k --user 0 com.google.android.apps.googleassistant
adb shell pm uninstall -k --user 0 com.google.android.apps.maps
adb shell pm uninstall -k --user 0 com.google.android.apps.messaging
adb shell pm uninstall -k --user 0 com.google.android.apps.nbu.files
adb shell pm uninstall -k --user 0 com.google.android.apps.photos
adb shell pm uninstall -k --user 0 com.google.android.apps.plus
adb shell pm uninstall -k --user 0 com.google.android.apps.tachyon
adb shell pm uninstall -k --user 0 com.google.android.apps.turbo
adb shell pm uninstall -k --user 0 com.google.android.apps.wellbeing
adb shell pm uninstall -k --user 0 com.google.android.apps.youtube.music
adb shell pm uninstall -k --user 0 com.google.android.backuptransport
adb shell pm uninstall -k --user 0 com.google.android.cellbroadcastreceiver
adb shell pm uninstall -k --user 0 com.google.android.documentsui
adb shell pm uninstall -k --user 0 com.google.android.feedback
adb shell pm uninstall -k --user 0 com.google.android.gm
adb shell pm uninstall -k --user 0 com.google.android.gms
adb shell pm uninstall -k --user 0 com.google.android.gms.location.history
adb shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall -k --user 0 com.google.android.inputmethod.latin
adb shell pm uninstall -k --user 0 com.google.android.marvin.talkback
adb shell pm uninstall -k --user 0 com.google.android.music
adb shell pm uninstall -k --user 0 com.google.android.partnersetup
adb shell pm uninstall -k --user 0 com.google.android.projection.gearhead
adb shell pm uninstall -k --user 0 com.google.android.syncadapters.calendar
adb shell pm uninstall -k --user 0 com.google.android.tts
adb shell pm uninstall -k --user 0 com.google.android.videos
adb shell pm uninstall -k --user 0 com.google.android.youtube
adb shell pm uninstall -k --user 0 com.google.ar.core
adb shell pm uninstall -k --user 0 com.hicloud.android.clone
adb shell pm uninstall -k --user 0 com.huawei.android.chr
adb shell pm uninstall -k --user 0 com.huawei.android.hwaps
adb shell pm uninstall -k --user 0 com.huawei.android.hwouc
adb shell pm uninstall -k --user 0 com.huawei.android.karaoke
adb shell pm uninstall -k --user 0 com.huawei.android.pushagent
adb shell pm uninstall -k --user 0 com.huawei.android.totemweather
adb shell pm uninstall -k --user 0 com.huawei.appmarket
adb shell pm uninstall -k --user 0 com.huawei.fido.uafclient
adb shell pm uninstall -k --user 0 com.huawei.gameassistant
adb shell pm uninstall -k --user 0 com.huawei.health
adb shell pm uninstall -k --user 0 com.huawei.hidisk
adb shell pm uninstall -k --user 0 com.huawei.himovie.overseas
adb shell pm uninstall -k --user 0 com.huawei.honorclub.android
adb shell pm uninstall -k --user 0 com.huawei.hwasm
adb shell pm uninstall -k --user 0 com.huawei.mmitest
adb shell pm uninstall -k --user 0 com.huawei.mmitest 
adb shell pm uninstall -k --user 0 com.huawei.parentcontrol
adb shell pm uninstall -k --user 0 com.huawei.phoneservise
adb shell pm uninstall -k --user 0 com.huawei.printservice
adb shell pm uninstall -k --user 0 com.huawei.search
adb shell pm uninstall -k --user 0 com.idea.questionnaire
adb shell pm uninstall -k --user 0 com.joom
adb shell pm uninstall -k --user 0 com.lenovo.anyshare.gps
adb shell pm uninstall -k --user 0 com.lenovo.lps.cloud.sync.row
adb shell pm uninstall -k --user 0 com.microsoft.skydrive
adb shell pm uninstall -k --user 0 com.my.games.vendorapp
adb shell pm uninstall -k --user 0 com.netflix.mediaclient
adb shell pm uninstall -k --user 0 com.osp.app.signin
adb shell pm uninstall -k --user 0 com.reallytek.wg
adb shell pm uninstall -k --user 0 com.rlk.mi
adb shell pm uninstall -k --user 0 com.rlk.weathers
adb shell pm uninstall -k --user 0 com.samsung.android.app.omcagent
adb shell pm uninstall -k --user 0 com.samsung.android.app.settings.bixby
adb shell pm uninstall -k --user 0 com.samsung.android.calendar
adb shell pm uninstall -k --user 0 com.samsung.android.honeyboard
adb shell pm uninstall -k --user 0 com.samsung.android.kgclient
adb shell pm uninstall -k --user 0 com.samsung.android.kidsinstaller
adb shell pm uninstall -k --user 0 com.samsung.android.mapsagent
adb shell pm uninstall -k --user 0 com.samsung.android.providers.contacts
adb shell pm uninstall -k --user 0 com.samsung.android.rubin.app
adb shell pm uninstall -k --user 0 com.samsung.android.scloud
adb shell pm uninstall -k --user 0 com.samsung.android.themestore
adb shell pm uninstall -k --user 0 com.samsung.android.video
adb shell pm uninstall -k --user 0 com.samsung.app.newtrim
adb shell pm uninstall -k --user 0 com.sec.android.app.camera
adb shell pm uninstall -k --user 0 com.sec.android.app.chromecustomizations
adb shell pm uninstall -k --user 0 com.sec.android.app.myfiles
adb shell pm uninstall -k --user 0 com.sec.android.app.samsungapps
adb shell pm uninstall -k --user 0 com.sec.android.daemonapp
adb shell pm uninstall -k --user 0 com.sec.android.easyonehand
adb shell pm uninstall -k --user 0 com.sec.android.gallery3d
adb shell pm uninstall -k --user 0 com.sh.smart.caller
adb shell pm uninstall -k --user 0 com.smartlife.nebula
adb shell pm uninstall -k --user 0 com.swiftkey.swiftkey.configurator
adb shell pm uninstall -k --user 0 com.talpa.share
adb shell pm uninstall -k --user 0 com.touchtype.swiftkey
adb shell pm uninstall -k --user 0 com.transsion.agingfunction
adb shell pm uninstall -k --user 0 com.transsion.applock
adb shell pm uninstall -k --user 0 com.transsion.audioshare
adb shell pm uninstall -k --user 0 com.transsion.calculator
adb shell pm uninstall -k --user 0 com.transsion.calendar
adb shell pm uninstall -k --user 0 com.transsion.camera
adb shell pm uninstall -k --user 0 com.transsion.carlcare
adb shell pm uninstall -k --user 0 com.transsion.childmode
adb shell pm uninstall -k --user 0 com.transsion.childmode.resoverlay
adb shell pm uninstall -k --user 0 com.transsion.faceid
adb shell pm uninstall -k --user 0 com.transsion.faceidsub
adb shell pm uninstall -k --user 0 com.transsion.filemanagerx
adb shell pm uninstall -k --user 0 com.transsion.fmradio
adb shell pm uninstall -k --user 0 com.transsion.health
adb shell pm uninstall -k --user 0 com.transsion.hilauncher
adb shell pm uninstall -k --user 0 com.transsion.hiparty
adb shell pm uninstall -k --user 0 com.transsion.kolun.assistant
adb shell pm uninstall -k --user 0 com.transsion.letswitch
adb shell pm uninstall -k --user 0 com.transsion.magazineservice.hios
adb shell pm uninstall -k --user 0 com.transsion.magicshow
adb shell pm uninstall -k --user 0 com.transsion.phonemanager
adb shell pm uninstall -k --user 0 com.transsion.phonemaster
adb shell pm uninstall -k --user 0 com.transsion.soundrecorder
adb shell pm uninstall -k --user 0 com.transsion.tabe
adb shell pm uninstall -k --user 0 com.transsion.trancare
adb shell pm uninstall -k --user 0 com.transsion.videocallenhancer
adb shell pm uninstall -k --user 0 com.transsion.wezone
adb shell pm uninstall -k --user 0 com.transsnet.store
adb shell pm uninstall -k --user 0 com.vk.clips
adb shell pm uninstall -k --user 0 com.vkontakte.android
adb shell pm uninstall -k --user 0 com.wssyncmldm
adb shell pm uninstall -k --user 0 com.xui.xhide
adb shell pm uninstall -k --user 0 com.yandex.zen
adb shell pm uninstall -k --user 0 com.zaz.translate
adb shell pm uninstall -k --user 0 dsi.ant.plugins.antplus
adb shell pm uninstall -k --user 0 dsi.ant.sample.acquirechannels
adb shell pm uninstall -k --user 0 dsi.ant.service.socket
adb shell pm uninstall -k --user 0 Enhance.gameservice
adb shell pm uninstall -k --user 0 facebook.appmanager
adb shell pm uninstall -k --user 0 facebook.katana
adb shell pm uninstall -k --user 0 facebook.services
adb shell pm uninstall -k --user 0 facebook.system
adb shell pm uninstall -k --user 0 google.android.apps.docs
adb shell pm uninstall -k --user 0 google.android.apps.maps
adb shell pm uninstall -k --user 0 google.android.apps.photos
adb shell pm uninstall -k --user 0 google.android.apps.tachyon
adb shell pm uninstall -k --user 0 google.android.apps.wellbeing
adb shell pm uninstall -k --user 0 google.android.feedback
adb shell pm uninstall -k --user 0 google.android.gm
adb shell pm uninstall -k --user 0 google.android.googlequicksearchbox
adb shell pm uninstall -k --user 0 google.android.inputmethod.latin
adb shell pm uninstall -k --user 0 google.android.marvin.talkback
adb shell pm uninstall -k --user 0 google.android.music
adb shell pm uninstall -k --user 0 google.android.printservice.recommendation
adb shell pm uninstall -k --user 0 google.android.syncadapters.calendar
adb shell pm uninstall -k --user 0 google.android.tts
adb shell pm uninstall -k --user 0 google.android.videos
adb shell pm uninstall -k --user 0 google.android.youtube
adb shell pm uninstall -k --user 0 google.ar.lens
adb shell pm uninstall -k --user 0 google.vr.vrcore
adb shell pm uninstall -k --user 0 mobeam.barcodeService
adb shell pm uninstall -k --user 0 motricity.verizon.ssodownloadable
adb shell pm uninstall -k --user 0 net.bat.store
adb shell pm uninstall -k --user 0 ru.auto.ara
adb shell pm uninstall -k --user 0 ru.dublgis.dgismobile
adb shell pm uninstall -k --user 0 ru.mail.mailapp
adb shell pm uninstall -k --user 0 ru.ozon.app.android
adb shell pm uninstall -k --user 0 ru.samsung.catalog
adb shell pm uninstall -k --user 0 ru.sportmaster.app
adb shell pm uninstall -k --user 0 ru.yandex.music.samsung
adb shell pm uninstall -k --user 0 ru.yandex.searchplugin
adb shell pm uninstall -k --user 0 samsung.android.app.aodservice
adb shell pm uninstall -k --user 0 samsung.android.app.appsedge
adb shell pm uninstall -k --user 0 samsung.android.app.camera.sticker.facearavatar.preload
adb shell pm uninstall -k --user 0 samsung.android.app.dressroom
adb shell pm uninstall -k --user 0 samsung.android.app.routines
adb shell pm uninstall -k --user 0 samsung.android.app.sbrowseredge
adb shell pm uninstall -k --user 0 samsung.android.app.social
adb shell pm uninstall -k --user 0 samsung.android.app.spage
adb shell pm uninstall -k --user 0 samsung.android.app.vrsetupwizardstub
adb shell pm uninstall -k --user 0 samsung.android.app.watchmanagerstub
adb shell pm uninstall -k --user 0 samsung.android.ardrawing
adb shell pm uninstall -k --user 0 samsung.android.aremoji
adb shell pm uninstall -k --user 0 samsung.android.authfw
adb shell pm uninstall -k --user 0 samsung.android.beaconmanager
adb shell pm uninstall -k --user 0 samsung.android.bixby.agent
adb shell pm uninstall -k --user 0 samsung.android.bixby.agent.dummy
adb shell pm uninstall -k --user 0 samsung.android.bixby.service
adb shell pm uninstall -k --user 0 samsung.android.bixby.wakeup
adb shell pm uninstall -k --user 0 samsung.android.bixbyvision.framework
adb shell pm uninstall -k --user 0 samsung.android.da.daagent
adb shell pm uninstall -k --user 0 samsung.android.drivelink.stub
adb shell pm uninstall -k --user 0 samsung.android.email.provider
adb shell pm uninstall -k --user 0 samsung.android.emojiupdater
adb shell pm uninstall -k --user 0 samsung.android.game.gamehome
adb shell pm uninstall -k --user 0 samsung.android.game.gametools
adb shell pm uninstall -k --user 0 samsung.android.game.gos
adb shell pm uninstall -k --user 0 samsung.android.gametuner.thin
adb shell pm uninstall -k --user 0 samsung.android.hmt.vrshell
adb shell pm uninstall -k --user 0 samsung.android.hmt.vrsvc
adb shell pm uninstall -k --user 0 samsung.android.kidsinstaller
adb shell pm uninstall -k --user 0 samsung.android.mateagent
adb shell pm uninstall -k --user 0 samsung.android.messaging
adb shell pm uninstall -k --user 0 samsung.android.oneconnect
adb shell pm uninstall -k --user 0 samsung.android.samsungpass
adb shell pm uninstall -k --user 0 samsung.android.samsungpassautofill
adb shell pm uninstall -k --user 0 samsung.android.scloud
adb shell pm uninstall -k --user 0 samsung.android.sdk.handwriting
adb shell pm uninstall -k --user 0 samsung.android.sdk.professionaludio.utility.jammonitor
adb shell pm uninstall -k --user 0 samsung.android.service.aircommand
adb shell pm uninstall -k --user 0 samsung.android.service.livedrawing
adb shell pm uninstall -k --user 0 samsung.android.service.peoplestripe
adb shell pm uninstall -k --user 0 samsung.android.spay
adb shell pm uninstall -k --user 0 samsung.android.spayfw
adb shell pm uninstall -k --user 0 samsung.android.svoiceime
adb shell pm uninstall -k --user 0 samsung.android.universalswitch
adb shell pm uninstall -k --user 0 samsung.android.visioncloudagent
adb shell pm uninstall -k --user 0 samsung.android.visionintelligence
adb shell pm uninstall -k --user 0 samsung.android.voc
adb shell pm uninstall -k --user 0 samsung.android.wellbeing
adb shell pm uninstall -k --user 0 samsung.android.widgetapp.yahooedge.finance
adb shell pm uninstall -k --user 0 samsung.android.widgetapp.yahooedge.sport
adb shell pm uninstall -k --user 0 samsung.app.highlightplayer
adb shell pm uninstall -k --user 0 samsung.attvvm
adb shell pm uninstall -k --user 0 samsung.desktopsystemui
adb shell pm uninstall -k --user 0 samsung.ecomm.global
adb shell pm uninstall -k --user 0 samsung.safetyinformation
adb shell pm uninstall -k --user 0 samsung.storyservice
adb shell pm uninstall -k --user 0 samsung.vmmhux
adb shell pm uninstall -k --user 0 samsung.vvm
adb shell pm uninstall -k --user 0 sec.android.app.chromecustomizations
adb shell pm uninstall -k --user 0 sec.android.app.desktoplauncher
adb shell pm uninstall -k --user 0 sec.android.app.dexonpc
adb shell pm uninstall -k --user 0 sec.android.app.kidshome
adb shell pm uninstall -k --user 0 sec.android.app.popupcalculator
adb shell pm uninstall -k --user 0 sec.android.app.sbrowser
adb shell pm uninstall -k --user 0 sec.android.app.voicenote
adb shell pm uninstall -k --user 0 sec.android.daemonapp
adb shell pm uninstall -k --user 0 sec.android.desktopmode.uiservice
adb shell pm uninstall -k --user 0 sec.android.easyMover.Agent
adb shell pm uninstall -k --user 0 sec.android.easyonehand
adb shell pm uninstall -k --user 0 sec.android.mimage.avatarstickers
adb shell pm uninstall -k --user 0 sec.android.splitsound
adb shell pm uninstall -k --user 0 sec.android.widgetapp.samsungapps
adb shell pm uninstall -k --user 0 vcast.mediamanager
adb shell pm uninstall -k --user 0 vzw.hs.android.modlite
adb shell pm uninstall -k --user 0 vzw.hss.myverizon
adb shell pm uninstall -k --user 0 wsomacp
