adb.exe shell pm uninstall -k --user 0 android.bips
adb.exe shell pm uninstall -k --user 0 android.bookmarkprovider
adb.exe shell pm uninstall -k --user 0 android.browser
adb.exe shell pm uninstall -k --user 0 android.calendar
adb.exe shell pm uninstall -k --user 0 android.cellbroadcastreceiver
adb.exe shell pm uninstall -k --user 0 android.cellbroadcastreceiver.overlay.common
adb.exe shell pm uninstall -k --user 0 android.chrome
adb.exe shell pm uninstall -k --user 0 android.deskclock
adb.exe shell pm uninstall -k --user 0 android.dreams.basic
adb.exe shell pm uninstall -k --user 0 android.dreams.phototable
adb.exe shell pm uninstall -k --user 0 android.egg
adb.exe shell pm uninstall -k --user 0 android.emergency
adb.exe shell pm uninstall -k --user 0 android.hotwordenrollment.okgoogle
adb.exe shell pm uninstall -k --user 0 android.mms
adb.exe shell pm uninstall -k --user 0 android.mms.service
adb.exe shell pm uninstall -k --user 0 android.printspooler
adb.exe shell pm uninstall -k --user 0 android.providers.downloads.ui
adb.exe shell pm uninstall -k --user 0 android.providers.partnerbookmarks
adb.exe shell pm uninstall -k --user 0 android.sharedstoragebackup
adb.exe shell pm uninstall -k --user 0 android.statementservice
adb.exe shell pm uninstall -k --user 0 android.stk
adb.exe shell pm uninstall -k --user 0 android.wallpaper.livepicker
adb.exe shell pm uninstall -k --user 0 android.wallpaperbackup
adb.exe shell pm uninstall -k --user 0 android.wallpapercropper
adb.exe shell pm uninstall -k --user 0 asurion.android.protech.att
adb.exe shell pm uninstall -k --user 0 asurion.android.verizon.vms
adb.exe shell pm uninstall -k --user 0 att.android.attsmartwifi
adb.exe shell pm uninstall -k --user 0 att.dtv.shaderemote
adb.exe shell pm uninstall -k --user 0 att.myWireless
adb.exe shell pm uninstall -k --user 0 att.tv
adb.exe shell pm uninstall -k --user 0 boxer.app
adb.exe shell pm uninstall -k --user 0 cn.wps.moffice_eng
adb.exe shell pm uninstall -k --user 0 cnn.mobile.android.phone.edgepanel
adb.exe shell pm uninstall -k --user 0 com.afmobi.boomplayer
adb.exe shell pm uninstall -k --user 0 com.android.apps.tag
adb.exe shell pm uninstall -k --user 0 com.android.bookmarkprovider
adb.exe shell pm uninstall -k --user 0 com.android.calendar
adb.exe shell pm uninstall -k --user 0 com.android.chrome
adb.exe shell pm uninstall -k --user 0 com.android.egg
adb.exe shell pm uninstall -k --user 0 com.android.emergency
adb.exe shell pm uninstall -k --user 0 com.android.gallery3d
adb.exe shell pm uninstall -k --user 0 com.android.htmlviewer
adb.exe shell pm uninstall -k --user 0 com.android.imedia.syncplay
adb.exe shell pm uninstall -k --user 0 com.android.mbash
adb.exe shell pm uninstall -k --user 0 com.android.mediacenter
adb.exe shell pm uninstall -k --user 0 com.android.printspooler
adb.exe shell pm uninstall -k --user 0 com.android.providers.calendar
adb.exe shell pm uninstall -k --user 0 com.android.providers.partnerbookmarks
adb.exe shell pm uninstall -k --user 0 com.android.stk
adb.exe shell pm uninstall -k --user 0 com.android.stk2
adb.exe shell pm uninstall -k --user 0 com.android.vending
adb.exe shell pm uninstall -k --user 0 com.android.wallpaper.livepicker
adb.exe shell pm uninstall -k --user 0 com.aura.oobe.samsung.gl
adb.exe shell pm uninstall -k --user 0 com.booking
adb.exe shell pm uninstall -k --user 0 com.example.android.notepad
adb.exe shell pm uninstall -k --user 0 com.facebook.appmanager
adb.exe shell pm uninstall -k --user 0 com.facebook.katana
adb.exe shell pm uninstall -k --user 0 com.facebook.services
adb.exe shell pm uninstall -k --user 0 com.facebook.system
adb.exe shell pm uninstall -k --user 0 com.facemoji.lite.transsion
adb.exe shell pm uninstall -k --user 0 com.funbase.xradio
adb.exe shell pm uninstall -k --user 0 com.gallery20
adb.exe shell pm uninstall -k --user 0 com.GMA.Ball.Sort.Puzzle
adb.exe shell pm uninstall -k --user 0 com.gma.water.sort.puzzle
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.docs
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.docs
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.sheets
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.docs.editors.slides
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.googleassistant
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.maps
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.messaging
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.nbu.files
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.photos
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.plus
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.tachyon
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.turbo
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.wellbeing
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.youtube.music
adb.exe shell pm uninstall -k --user 0 com.google.android.backuptransport
adb.exe shell pm uninstall -k --user 0 com.google.android.cellbroadcastreceiver
adb.exe shell pm uninstall -k --user 0 com.google.android.documentsui
adb.exe shell pm uninstall -k --user 0 com.google.android.feedback
adb.exe shell pm uninstall -k --user 0 com.google.android.gm
adb.exe shell pm uninstall -k --user 0 com.google.android.gms
adb.exe shell pm uninstall -k --user 0 com.google.android.gms.location.history
adb.exe shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox
adb.exe shell pm uninstall -k --user 0 com.google.android.inputmethod.latin
adb.exe shell pm uninstall -k --user 0 com.google.android.marvin.talkback
adb.exe shell pm uninstall -k --user 0 com.google.android.music
adb.exe shell pm uninstall -k --user 0 com.google.android.partnersetup
adb.exe shell pm uninstall -k --user 0 com.google.android.projection.gearhead
adb.exe shell pm uninstall -k --user 0 com.google.android.syncadapters.calendar
adb.exe shell pm uninstall -k --user 0 com.google.android.tts
adb.exe shell pm uninstall -k --user 0 com.google.android.videos
adb.exe shell pm uninstall -k --user 0 com.google.android.youtube
adb.exe shell pm uninstall -k --user 0 com.google.ar.core
adb.exe shell pm uninstall -k --user 0 com.hicloud.android.clone
adb.exe shell pm uninstall -k --user 0 com.huawei.android.chr
adb.exe shell pm uninstall -k --user 0 com.huawei.android.hwaps
adb.exe shell pm uninstall -k --user 0 com.huawei.android.hwouc
adb.exe shell pm uninstall -k --user 0 com.huawei.android.karaoke
adb.exe shell pm uninstall -k --user 0 com.huawei.android.pushagent
adb.exe shell pm uninstall -k --user 0 com.huawei.android.totemweather
adb.exe shell pm uninstall -k --user 0 com.huawei.appmarket
adb.exe shell pm uninstall -k --user 0 com.huawei.fido.uafclient
adb.exe shell pm uninstall -k --user 0 com.huawei.gameassistant
adb.exe shell pm uninstall -k --user 0 com.huawei.health
adb.exe shell pm uninstall -k --user 0 com.huawei.hidisk
adb.exe shell pm uninstall -k --user 0 com.huawei.himovie.overseas
adb.exe shell pm uninstall -k --user 0 com.huawei.honorclub.android
adb.exe shell pm uninstall -k --user 0 com.huawei.hwasm
adb.exe shell pm uninstall -k --user 0 com.huawei.mmitest
adb.exe shell pm uninstall -k --user 0 com.huawei.mmitest 
adb.exe shell pm uninstall -k --user 0 com.huawei.parentcontrol
adb.exe shell pm uninstall -k --user 0 com.huawei.phoneservise
adb.exe shell pm uninstall -k --user 0 com.huawei.printservice
adb.exe shell pm uninstall -k --user 0 com.huawei.search
adb.exe shell pm uninstall -k --user 0 com.idea.questionnaire
adb.exe shell pm uninstall -k --user 0 com.joom
adb.exe shell pm uninstall -k --user 0 com.lenovo.anyshare.gps
adb.exe shell pm uninstall -k --user 0 com.lenovo.lps.cloud.sync.row
adb.exe shell pm uninstall -k --user 0 com.microsoft.skydrive
adb.exe shell pm uninstall -k --user 0 com.my.games.vendorapp
adb.exe shell pm uninstall -k --user 0 com.netflix.mediaclient
adb.exe shell pm uninstall -k --user 0 com.osp.app.signin
adb.exe shell pm uninstall -k --user 0 com.reallytek.wg
adb.exe shell pm uninstall -k --user 0 com.rlk.mi
adb.exe shell pm uninstall -k --user 0 com.rlk.weathers
adb.exe shell pm uninstall -k --user 0 com.samsung.android.app.omcagent
adb.exe shell pm uninstall -k --user 0 com.samsung.android.app.settings.bixby
adb.exe shell pm uninstall -k --user 0 com.samsung.android.calendar
adb.exe shell pm uninstall -k --user 0 com.samsung.android.honeyboard
adb.exe shell pm uninstall -k --user 0 com.samsung.android.kgclient
adb.exe shell pm uninstall -k --user 0 com.samsung.android.kidsinstaller
adb.exe shell pm uninstall -k --user 0 com.samsung.android.mapsagent
adb.exe shell pm uninstall -k --user 0 com.samsung.android.providers.contacts
adb.exe shell pm uninstall -k --user 0 com.samsung.android.rubin.app
adb.exe shell pm uninstall -k --user 0 com.samsung.android.scloud
adb.exe shell pm uninstall -k --user 0 com.samsung.android.themestore
adb.exe shell pm uninstall -k --user 0 com.samsung.android.video
adb.exe shell pm uninstall -k --user 0 com.samsung.app.newtrim
adb.exe shell pm uninstall -k --user 0 com.sec.android.app.camera
adb.exe shell pm uninstall -k --user 0 com.sec.android.app.chromecustomizations
adb.exe shell pm uninstall -k --user 0 com.sec.android.app.myfiles
adb.exe shell pm uninstall -k --user 0 com.sec.android.app.samsungapps
adb.exe shell pm uninstall -k --user 0 com.sec.android.daemonapp
adb.exe shell pm uninstall -k --user 0 com.sec.android.easyonehand
adb.exe shell pm uninstall -k --user 0 com.sec.android.gallery3d
adb.exe shell pm uninstall -k --user 0 com.sh.smart.caller
adb.exe shell pm uninstall -k --user 0 com.smartlife.nebula
adb.exe shell pm uninstall -k --user 0 com.swiftkey.swiftkey.configurator
adb.exe shell pm uninstall -k --user 0 com.talpa.share
adb.exe shell pm uninstall -k --user 0 com.touchtype.swiftkey
adb.exe shell pm uninstall -k --user 0 com.transsion.agingfunction
adb.exe shell pm uninstall -k --user 0 com.transsion.applock
adb.exe shell pm uninstall -k --user 0 com.transsion.audioshare
adb.exe shell pm uninstall -k --user 0 com.transsion.calculator
adb.exe shell pm uninstall -k --user 0 com.transsion.calendar
adb.exe shell pm uninstall -k --user 0 com.transsion.camera
adb.exe shell pm uninstall -k --user 0 com.transsion.carlcare
adb.exe shell pm uninstall -k --user 0 com.transsion.childmode
adb.exe shell pm uninstall -k --user 0 com.transsion.childmode.resoverlay
adb.exe shell pm uninstall -k --user 0 com.transsion.faceid
adb.exe shell pm uninstall -k --user 0 com.transsion.faceidsub
adb.exe shell pm uninstall -k --user 0 com.transsion.filemanagerx
adb.exe shell pm uninstall -k --user 0 com.transsion.fmradio
adb.exe shell pm uninstall -k --user 0 com.transsion.health
adb.exe shell pm uninstall -k --user 0 com.transsion.hilauncher
adb.exe shell pm uninstall -k --user 0 com.transsion.hiparty
adb.exe shell pm uninstall -k --user 0 com.transsion.kolun.assistant
adb.exe shell pm uninstall -k --user 0 com.transsion.letswitch
adb.exe shell pm uninstall -k --user 0 com.transsion.magazineservice.hios
adb.exe shell pm uninstall -k --user 0 com.transsion.magicshow
adb.exe shell pm uninstall -k --user 0 com.transsion.phonemanager
adb.exe shell pm uninstall -k --user 0 com.transsion.phonemaster
adb.exe shell pm uninstall -k --user 0 com.transsion.soundrecorder
adb.exe shell pm uninstall -k --user 0 com.transsion.tabe
adb.exe shell pm uninstall -k --user 0 com.transsion.trancare
adb.exe shell pm uninstall -k --user 0 com.transsion.videocallenhancer
adb.exe shell pm uninstall -k --user 0 com.transsion.wezone
adb.exe shell pm uninstall -k --user 0 com.transsnet.store
adb.exe shell pm uninstall -k --user 0 com.vk.clips
adb.exe shell pm uninstall -k --user 0 com.vkontakte.android
adb.exe shell pm uninstall -k --user 0 com.wssyncmldm
adb.exe shell pm uninstall -k --user 0 com.xui.xhide
adb.exe shell pm uninstall -k --user 0 com.yandex.zen
adb.exe shell pm uninstall -k --user 0 com.zaz.translate
adb.exe shell pm uninstall -k --user 0 dsi.ant.plugins.antplus
adb.exe shell pm uninstall -k --user 0 dsi.ant.sample.acquirechannels
adb.exe shell pm uninstall -k --user 0 dsi.ant.service.socket
adb.exe shell pm uninstall -k --user 0 Enhance.gameservice
adb.exe shell pm uninstall -k --user 0 facebook.appmanager
adb.exe shell pm uninstall -k --user 0 facebook.katana
adb.exe shell pm uninstall -k --user 0 facebook.services
adb.exe shell pm uninstall -k --user 0 facebook.system
adb.exe shell pm uninstall -k --user 0 google.android.apps.docs
adb.exe shell pm uninstall -k --user 0 google.android.apps.maps
adb.exe shell pm uninstall -k --user 0 google.android.apps.photos
adb.exe shell pm uninstall -k --user 0 google.android.apps.tachyon
adb.exe shell pm uninstall -k --user 0 google.android.apps.wellbeing
adb.exe shell pm uninstall -k --user 0 google.android.feedback
adb.exe shell pm uninstall -k --user 0 google.android.gm
adb.exe shell pm uninstall -k --user 0 google.android.googlequicksearchbox
adb.exe shell pm uninstall -k --user 0 google.android.inputmethod.latin
adb.exe shell pm uninstall -k --user 0 google.android.marvin.talkback
adb.exe shell pm uninstall -k --user 0 google.android.music
adb.exe shell pm uninstall -k --user 0 google.android.printservice.recommendation
adb.exe shell pm uninstall -k --user 0 google.android.syncadapters.calendar
adb.exe shell pm uninstall -k --user 0 google.android.tts
adb.exe shell pm uninstall -k --user 0 google.android.videos
adb.exe shell pm uninstall -k --user 0 google.android.youtube
adb.exe shell pm uninstall -k --user 0 google.ar.lens
adb.exe shell pm uninstall -k --user 0 google.vr.vrcore
adb.exe shell pm uninstall -k --user 0 mobeam.barcodeService
adb.exe shell pm uninstall -k --user 0 motricity.verizon.ssodownloadable
adb.exe shell pm uninstall -k --user 0 net.bat.store
adb.exe shell pm uninstall -k --user 0 ru.auto.ara
adb.exe shell pm uninstall -k --user 0 ru.dublgis.dgismobile
adb.exe shell pm uninstall -k --user 0 ru.mail.mailapp
adb.exe shell pm uninstall -k --user 0 ru.ozon.app.android
adb.exe shell pm uninstall -k --user 0 ru.samsung.catalog
adb.exe shell pm uninstall -k --user 0 ru.sportmaster.app
adb.exe shell pm uninstall -k --user 0 ru.yandex.music.samsung
adb.exe shell pm uninstall -k --user 0 ru.yandex.searchplugin
adb.exe shell pm uninstall -k --user 0 samsung.android.app.aodservice
adb.exe shell pm uninstall -k --user 0 samsung.android.app.appsedge
adb.exe shell pm uninstall -k --user 0 samsung.android.app.camera.sticker.facearavatar.preload
adb.exe shell pm uninstall -k --user 0 samsung.android.app.dressroom
adb.exe shell pm uninstall -k --user 0 samsung.android.app.routines
adb.exe shell pm uninstall -k --user 0 samsung.android.app.sbrowseredge
adb.exe shell pm uninstall -k --user 0 samsung.android.app.social
adb.exe shell pm uninstall -k --user 0 samsung.android.app.spage
adb.exe shell pm uninstall -k --user 0 samsung.android.app.vrsetupwizardstub
adb.exe shell pm uninstall -k --user 0 samsung.android.app.watchmanagerstub
adb.exe shell pm uninstall -k --user 0 samsung.android.ardrawing
adb.exe shell pm uninstall -k --user 0 samsung.android.aremoji
adb.exe shell pm uninstall -k --user 0 samsung.android.authfw
adb.exe shell pm uninstall -k --user 0 samsung.android.beaconmanager
adb.exe shell pm uninstall -k --user 0 samsung.android.bixby.agent
adb.exe shell pm uninstall -k --user 0 samsung.android.bixby.agent.dummy
adb.exe shell pm uninstall -k --user 0 samsung.android.bixby.service
adb.exe shell pm uninstall -k --user 0 samsung.android.bixby.wakeup
adb.exe shell pm uninstall -k --user 0 samsung.android.bixbyvision.framework
adb.exe shell pm uninstall -k --user 0 samsung.android.da.daagent
adb.exe shell pm uninstall -k --user 0 samsung.android.drivelink.stub
adb.exe shell pm uninstall -k --user 0 samsung.android.email.provider
adb.exe shell pm uninstall -k --user 0 samsung.android.emojiupdater
adb.exe shell pm uninstall -k --user 0 samsung.android.game.gamehome
adb.exe shell pm uninstall -k --user 0 samsung.android.game.gametools
adb.exe shell pm uninstall -k --user 0 samsung.android.game.gos
adb.exe shell pm uninstall -k --user 0 samsung.android.gametuner.thin
adb.exe shell pm uninstall -k --user 0 samsung.android.hmt.vrshell
adb.exe shell pm uninstall -k --user 0 samsung.android.hmt.vrsvc
adb.exe shell pm uninstall -k --user 0 samsung.android.kidsinstaller
adb.exe shell pm uninstall -k --user 0 samsung.android.mateagent
adb.exe shell pm uninstall -k --user 0 samsung.android.messaging
adb.exe shell pm uninstall -k --user 0 samsung.android.oneconnect
adb.exe shell pm uninstall -k --user 0 samsung.android.samsungpass
adb.exe shell pm uninstall -k --user 0 samsung.android.samsungpassautofill
adb.exe shell pm uninstall -k --user 0 samsung.android.scloud
adb.exe shell pm uninstall -k --user 0 samsung.android.sdk.handwriting
adb.exe shell pm uninstall -k --user 0 samsung.android.sdk.professionaludio.utility.jammonitor
adb.exe shell pm uninstall -k --user 0 samsung.android.service.aircommand
adb.exe shell pm uninstall -k --user 0 samsung.android.service.livedrawing
adb.exe shell pm uninstall -k --user 0 samsung.android.service.peoplestripe
adb.exe shell pm uninstall -k --user 0 samsung.android.spay
adb.exe shell pm uninstall -k --user 0 samsung.android.spayfw
adb.exe shell pm uninstall -k --user 0 samsung.android.svoiceime
adb.exe shell pm uninstall -k --user 0 samsung.android.universalswitch
adb.exe shell pm uninstall -k --user 0 samsung.android.visioncloudagent
adb.exe shell pm uninstall -k --user 0 samsung.android.visionintelligence
adb.exe shell pm uninstall -k --user 0 samsung.android.voc
adb.exe shell pm uninstall -k --user 0 samsung.android.wellbeing
adb.exe shell pm uninstall -k --user 0 samsung.android.widgetapp.yahooedge.finance
adb.exe shell pm uninstall -k --user 0 samsung.android.widgetapp.yahooedge.sport
adb.exe shell pm uninstall -k --user 0 samsung.app.highlightplayer
adb.exe shell pm uninstall -k --user 0 samsung.attvvm
adb.exe shell pm uninstall -k --user 0 samsung.desktopsystemui
adb.exe shell pm uninstall -k --user 0 samsung.ecomm.global
adb.exe shell pm uninstall -k --user 0 samsung.safetyinformation
adb.exe shell pm uninstall -k --user 0 samsung.storyservice
adb.exe shell pm uninstall -k --user 0 samsung.vmmhux
adb.exe shell pm uninstall -k --user 0 samsung.vvm
adb.exe shell pm uninstall -k --user 0 sec.android.app.chromecustomizations
adb.exe shell pm uninstall -k --user 0 sec.android.app.desktoplauncher
adb.exe shell pm uninstall -k --user 0 sec.android.app.dexonpc
adb.exe shell pm uninstall -k --user 0 sec.android.app.kidshome
adb.exe shell pm uninstall -k --user 0 sec.android.app.popupcalculator
adb.exe shell pm uninstall -k --user 0 sec.android.app.sbrowser
adb.exe shell pm uninstall -k --user 0 sec.android.app.voicenote
adb.exe shell pm uninstall -k --user 0 sec.android.daemonapp
adb.exe shell pm uninstall -k --user 0 sec.android.desktopmode.uiservice
adb.exe shell pm uninstall -k --user 0 sec.android.easyMover.Agent
adb.exe shell pm uninstall -k --user 0 sec.android.easyonehand
adb.exe shell pm uninstall -k --user 0 sec.android.mimage.avatarstickers
adb.exe shell pm uninstall -k --user 0 sec.android.splitsound
adb.exe shell pm uninstall -k --user 0 sec.android.widgetapp.samsungapps
adb.exe shell pm uninstall -k --user 0 vcast.mediamanager
adb.exe shell pm uninstall -k --user 0 vzw.hs.android.modlite
adb.exe shell pm uninstall -k --user 0 vzw.hss.myverizon
adb.exe shell pm uninstall -k --user 0 wsomacp
